/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2017-03-24 17:40:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ThiSinh_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Tuyển sinh</title>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Asset/Head.jsp", out, false);
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Asset/Header.jsp", out, false);
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Asset/Menu2.jsp", out, false);
      out.write("\r\n");
      out.write("<div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("<div class=\"row\">\r\n");
      out.write("\t<div class=\"col-md-4 no-pad\">\r\n");
      out.write("\t\t<div class=\"thongtinkithi group-content\">\r\n");
      out.write("\t\t\t<div class=\"main-nav\">\r\n");
      out.write("\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Asset/ThongTinKyThi.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t<div class=\"group-content\">\r\n");
      out.write("\t\t\t<div class=\"row main-nav\" >\r\n");
      out.write("\t\t\t\t<p class=\"title\">THÔNG TIN THÍ SINH DỰ THI</p>\r\n");
      out.write("\t\t\t\t<form action=\"\" class=\"form-horizontal\" method=\"POST\">\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-7\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-md-2 no-pad\" for=\"first-name\">Họ đệm:</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"first-name\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-md-2 no-pad\" for=\"birthday-place\">Nơi sinh:</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"birthday-place\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-md-2 no-pad\" for=\"Subjects\">Đối tượng:</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\" form-control\" name=\"Subjects\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">Anh hùng lao động</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">Thương binh liệt sĩ</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-md-2 no-pad\" for=\"email\">Email:</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-10\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"email\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"col-md-5 pad-5\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-md-4 no-pad\" for=\"last-name\">Tên:</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-8 \">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"last-name\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-md-4 no-pad\" for=\"birthday\">Ngày sinh:</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-8 \">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"birthday\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-md-4 no-pad\" for=\"area\">Khu vực:</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-8 \">\r\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"form-control\" name=\"area\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">Khu vực 1</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"\">Khu vực 2</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"form-group\">\r\n");
      out.write("\t\t\t\t\t\t\t<label class=\"col-md-4 no-pad\" for=\"phone\">Số điện thoại:</label>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-md-8\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" name=\"phone\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div><!-- end form-->\r\n");
      out.write("\t\t<div class=\"main-nav\">\r\n");
      out.write("\t\t\t<label for=\"address\">Địa chỉ liên hệ:</label>\r\n");
      out.write("\t\t\t<textarea class=\"form-control\" rows=\"4\" cols=\"100\" name=\"address\"></textarea>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"btn-gr\">\r\n");
      out.write("\t\t\t<button type=\"submit\" class=\"btn btn-success btn-all\" name='add'>Thêm</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" class=\"btn btn-success btn-all\" name='update'>Lưu</button>\r\n");
      out.write("\t\t\t<button type=\"submit\" class=\"btn btn-success btn-all\" name='delete'>Xoá</button>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div class=\"details_info\">\r\n");
      out.write("\t\t\t<p class=\"title\">DANH SÁCH CÁC THÍ SINH DỰ THI</p>\r\n");
      out.write("\t\t\t<table class=\"table table-bordered table-hover table-striped\">\r\n");
      out.write("\t\t\t\t<thead>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<th>STT</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Họ đệm</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Tên</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Ngày sinh</th>\r\n");
      out.write("\t\t\t\t\t\t<!-- <th>Email</th> -->\r\n");
      out.write("\t\t\t\t\t\t<th>Khu vực</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Đối tượng</th>\r\n");
      out.write("\t\t\t\t\t\t<!-- <th>Số điện thoại</th>\r\n");
      out.write("\t\t\t\t\t\t<th>Địa chỉ liên hệ</th> -->\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</thead>\r\n");
      out.write("\t\t\t\t<tbody>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>1</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Trần Nữ Như</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Quỳnh</td>\r\n");
      out.write("\t\t\t\t\t\t<td>26/05/1995</td>\r\n");
      out.write("\t\t\t\t\t\t<!-- <td>trannunhuquynh260595@gmail.com</td> -->\r\n");
      out.write("\t\t\t\t\t\t<td>Khu vực 2</td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<!-- <td>01648875899</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Quảng Bình</td> -->\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>2</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Trần Nữ Như</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Quỳnh</td>\r\n");
      out.write("\t\t\t\t\t\t<td>26/05/1995</td>\r\n");
      out.write("\t\t\t\t\t\t<!-- <td>trannunhuquynh260595@gmail.com</td> -->\r\n");
      out.write("\t\t\t\t\t\t<td>Khu vực 2</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Anh hùng lao động</td>\r\n");
      out.write("\t\t\t\t\t\t<!-- <td>01648875899</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Quảng Bình</td> -->\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td>3</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Trần Nữ Như</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Quỳnh</td>\r\n");
      out.write("\t\t\t\t\t\t<td>26/05/1995</td>\r\n");
      out.write("\t\t\t\t\t\t<!-- <td>trannunhuquynh260595@gmail.com</td> -->\r\n");
      out.write("\t\t\t\t\t\t<td>Khu vực 2</td>\r\n");
      out.write("\t\t\t\t\t\t<td></td>\r\n");
      out.write("\t\t\t\t\t\t<!-- <td>01648875899</td>\r\n");
      out.write("\t\t\t\t\t\t<td>Quảng Bình</td> -->\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t</tbody>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t<div class=\"totalCandidates\">\r\n");
      out.write("\t\t\t\t\t<p>Danh sách gồm có: <span> 50/100 </span> sinh viên</p>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t</div><!-- end details_info -->\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "Asset/Footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
